### ISSUE TITLE
Stuck at save sphere (Blitz)

### ISSUE THREAD

**Issue by orkaboy** [coderwilson/FFX_TAS_Python#207]
There still seems to be some bugs with disengage_save_sphere (or just before). TAS opens the save sphere, hops into blitz menu and gets stuck there.

Did not get this one on video, so I can't say the exact sequence of events that led up to it, but this is the traceback:
```
========================
Now touching save sphere.
[02:45:40.964] __main__     INFO     Keyboard Interrupt - Exiting.
[02:45:40.965] root         ERROR
Traceback (most recent call last):
  File "D:\dev\TAS\FFX_TAS_Python\main.py", line 500, in perform_TAS
    area.ne_armor.to_hidden_cave()
  File "D:\dev\TAS\FFX_TAS_Python\area\ne_armor.py", line 93, in to_hidden_cave
    save_sphere.touch_and_go()
  File "D:\dev\TAS\FFX_TAS_Python\save_sphere.py", line 104, in touch_and_go
    disengage_save_sphere()
  File "D:\dev\TAS\FFX_TAS_Python\save_sphere.py", line 99, in disengage_save_sphere
    xbox.tap_b()
  File "D:\dev\TAS\FFX_TAS_Python\xbox.py", line 333, in tap_b
    memory.main.wait_frames(1)
  File "D:\dev\TAS\FFX_TAS_Python\memory\main.py", line 182, in wait_frames
    current = process.readBytes(key, 4)
  File "D:\dev\TAS\FFX_TAS_Python\memory\main.py", line 45, in readBytes
    lp_number_of_bytes_read = ctypes.c_ulong(0)
KeyboardInterrupt
```

**Comment by coderwilson** [comment]
@orkaboy this should have been fixed with the latest PR merge (#209 I think). Please test this next version. If issue persists let me know, otherwise (hopefully) this will be an easy one to close.

**Comment by orkaboy** [comment]
Saw this again in my most recent run in same spot, but when I double checked the git history, saw that #209 hadn't been merged into my branch. Will test again and report if I see issues.

**Comment by orkaboy** [comment]
Completed a full-ish run, haven't seen this issue anymore in my last few. I'd say we can close it.
